### ISSUE TITLE
droptofloor issue

### ISSUE THREAD

**Issue by Baker7** [DarkPlacesEngine/darkplaces#102]
In Quake, by entity number, entities droptofloor in order.

In current dp beta but not April 19 dpbeta, the past behavior of DarkPlaces for droptofloor has changed.

![dpbeta_xon_hotel1](https://github.com/DarkPlacesEngine/darkplaces/assets/160253/0c23eb9b-8827-421d-afde-6210d6f63c71)

The television falls onto a television stand, the coffee maker falls onto a stand.

![dpbeta_hotel1](https://github.com/DarkPlacesEngine/darkplaces/assets/160253/4c055dd9-5957-4f47-82b4-2670db8553ae)

The pictured map is a q3 map called hotel1.bsp which I made, the download is available at https://www.moddb.com/mods/zircon-engine/downloads/quake3-quake1-single-player-tech-demo-alpha-1

I don't have an example of a Quake map that has entities fall on top of each other at the moment.

**Comment by bones-was-here** [comment]
The order in which entities are dropped by the droptofloor builtin is decided by SVQC.

Probably this changed because you depended on old bug(s): DP's droptofloor behaved quite differently than Quake's, including having entities collide that shouldn't, which broke id1 Quake and its expansions.  

If you want droptofloor behaviour that isn't compatible with Quake you would need to implement it in QC, like Xonotic does.

**Comment by Baker7** [comment]
Ok, cool.  I'm glad to hear new method is more compatible with Quake.
