### ISSUE TITLE
Can not play Alkaline 1.2 mod

### ISSUE THREAD

**Issue by hemebond** [DarkPlacesEngine/darkplaces#108]
The latest version 1.2 of the [Alkaline mod](https://www.slipseer.com/index.php?resources/alkaline.62/) does not load in the latest version of DarkPlaces.

Starting a new single player game or loading a map directly results in this error:

```
Server: DarkPlaces-Quake build 12:23:05 Oct 31 2023 - release (progs 30793 crc)
Serverinfo packet received.
Server protocol is DP7

<===================================>

Caustic Preserve
Failed to load sound "ambient/tornadosiren.wav"
BGM track 113 playing...
CL_SignonReply: 1
Not using buffered "dlcache/csprogs.dat.42302.62357" (buffered: (nil), 0)
Host_Error: client: CSQC_InputEvent not found in csprogs.dat
SV_Shutdown
Client "unconnected" dropped (Server shutting down)
CL_Disconnect
Sending clc_disconnect
Disconnected
Mem_Alloc: pool Renderer, file ../../../gl_rmain.c:3528, size 1048576000.000000 bytes (1000.000000 MB)
```

**Comment by Baker7** [comment]
Zircon plays those by unloading incompatible csqc progs.

In the Zircon source code, search for "r1414" and the changes are marked so that, for instance, DarkPlaces can more easily acquire the enhancement.  

"1414. Automatic unload of "fte csqc-lite" csprogs.dat allowing convenient play of these mods (see alk1.2.zip @ Quaddicted)
      This is an alternate CSQC that FTE/Quakespasm Spiked supports."

fte csqc-lite is a HUD only version of csqc.  Zircon loads the csqc, see that it does not have the required functions, prints a warning for the player and unloads the csqc.

**Comment by Baker7** [comment]
If you are wanting to do this ...

const char *PRVM_Prog_Load(prvm_prog_t *prog, const char *filename, unsigned char *data, int64_t size, int numrequiredfunc, const char **required_func, int numrequiredfields, prvm_required_field_t *required_field, int numrequiredglobals, prvm_required_field_t *required_global);

In Zircon Engine, PRVM_Prog_Load returns a string if a CSQC function is missing.

CSQC-Lite -- spike's "HUD only" CSQC -- is used by mods like Alkaline.  It does NOT have all the CSQC function that DarkPlaces requires.  

In CL_VM_Init ... if the load of csprogs.dat returns a missing function string, Zircon Engine unloads the csprogs.dat and ignores it and plays the game without it.

This requires the user to do nothing at all and they can still play Alkaline, except whatever custom HUD isn't used.

This is no different than what happens when you play Alkaline in regular Quakespasm.  Quakespasm does not have CSQC and does not load the HUD.

```
	// Baker r1414 - automatic unload of fte csqc-lite csprogs.dat
	const char *s_missing_fn = PRVM_Prog_Load(prog, csprogsname, csprogsdata, csprogsdatasize, cl_numrequiredfunc, cl_required_func, CL_REQFIELDS, cl_reqfields, CL_REQGLOBALS, cl_reqglobals);

	// Baker: See if csprogs supports DarkPlaces (pass is no guarantee, but we elim some)
	if (s_missing_fn) {
		Con_PrintLinef ("csprogs.dat not supported (DarkPlaces was not a target engine, lacks %s).  Unloading.", s_missing_fn);

		// unload
		PRVM_Prog_Reset(prog);
		cl.csqc_loaded = false;
		return;
	}

```
