### ISSUE TITLE
Rogue lavamen fall through floor

### ISSUE THREAD

**Issue by hemebond** [DarkPlacesEngine/darkplaces#109]
The [drop-through-floor](https://github.com/DarkPlacesEngine/darkplaces/commit/877af6733077c1f99756d9adf3eeca191d3bab86) fixes appear to break the Rogue lavamen in r2m3, causing them to fall through their lava basin to the floor below.

![image](https://github.com/DarkPlacesEngine/darkplaces/assets/424218/5be088d6-3e3d-4371-9082-2693b659ce85)

**Comment by hemebond** [comment]
Investigated this last night with bones_was_here and found that there is a clip brush in the lava that the `monster_lava_man` entities clip into when they spawn, causing `droptofloor()` to move them downwards.

Creating an .ent file with the following changes fixes the issues with the three of them:

```diff
@@ -1732,7 +1732,7 @@
 "angle" "0"
 "targetname" "t91"
 "classname" "monster_lava_man"
-"origin" "-904 -64 132"
+"origin" "-888 -64 132"
 "target" "t87"
 "spawnflags" "3"
 }
@@ -1740,7 +1740,7 @@
 "angle" "0"
 "targetname" "t93"
 "classname" "monster_lava_man"
-"origin" "-904 64 348"
+"origin" "-880 64 348"
 "target" "t88"
 "spawnflags" "3"
 }
@@ -1748,7 +1748,7 @@
 "angle" "180"
 "targetname" "t92"
 "classname" "monster_lava_man"
-"origin" "-192 -64 372"
+"origin" "-200 -64 372"
 "spawnflags" "3"
 "target" "t89"
 }
```

@bones-was-here Did you want to start a collection of .ent files in the repository that can be used to fix issues with the vanilla game and official mission packs? I can create a PR for this particular map.

**Comment by bones-was-here** [comment]
I'm still undecided about whether to add a cvar for this.  It won't fix anything, just allow the Q1BSP behaviour with buggy maps/QC to be changed.  Currently we match QSS-based engines and FTE, which works fine for id1 maps and is required by many community maps/mods.  The cvar might be useful for a few maps made for WinQuake or old versions of DP, we could use it by default when playing Rogue since we officially recognise it, but .ent files (or fixing the map/mod) are technically the better solution.

IMO we should use a separate repo in this project group for this kind of thing since it's not code and not relevant to many DP games.  There's also other repos still on svn that should be migrated over, with things like dlight files for id1 maps.
