### ISSUE TITLE
darkplaces-sdl2-vs2019 fails to build with error C2275 'msurface_t': expected an expression instead of a type

### ISSUE THREAD

**Issue by ghost** [DarkPlacesEngine/darkplaces#129]

**Comment by Baker7** [comment]
If you want a compiled one ...

https://beta.xonotic.org/autobuild/ <--- [betabeta](https://beta.xonotic.org/autobuild/Xonotic-20240210_4-engine.zip)

I know this compiles in Visual Studio 2019 -- but it is DarkPlaces Beta from March ...
https://github.com/KleskBY/DarkPlaces-Quake-SDK/tree/main/darkplaces-master

The instructions at https://quake.by/tutorials/?id=52 work with DarkPlaces Beta March 2023

I personally haven't downloaded a DarkPlaces Beta that quite compiled in Visual Studio out-of-the-box, the last time I tried there were errors like usage of "?:" operator that Visual Studio doesn't support which I saw in the changelog has been removed, but the DarkPlaces developers compile builds with mingw so the Visual Studio project files don't get much love.

If you are ok with something damn similar to DarkPlaces Beta that probably compiles in Visual Studio 2019 (it tends to compile in Visual Studio 2022) -- Zircon source code has a Visual Studio 2022 solution file and last time I tried it, it compiled a month ago (I use Mingw in CodeBlocks to compile because I can statically link SDL2, eliminating need for a separate SDL2.dll).

Zircon: https://www.moddb.com/mods/zircon-engine/  

https://quake.by/tutorials/?id=52

**Comment by FeatureRequestor** [comment]
> If you want a compiled one ...
> 
> https://beta.xonotic.org/autobuild/ <--- [betabeta](https://beta.xonotic.org/autobuild/Xonotic-20240210_4-engine.zip) -- if you are using it for Quake or non-Xonotic purposes, you need to start it with "-quake" command line parameter.
> 
> I know this compiles in Visual Studio 2019 -- but it is DarkPlaces Beta from March ... https://github.com/KleskBY/DarkPlaces-Quake-SDK/tree/main/darkplaces-master
> 
> The instructions at https://quake.by/tutorials/?id=52 work with DarkPlaces Beta March 2023
> 
> I personally haven't downloaded a DarkPlaces Beta that quite compiled in Visual Studio out-of-the-box, the last time I tried there were errors like usage of "?:" operator that Visual Studio doesn't support which I saw in the changelog has been removed, but the DarkPlaces developers compile builds with mingw so the Visual Studio project files don't get much love.
> 
> If you are ok with something damn similar to DarkPlaces Beta that probably compiles in Visual Studio 2019 (it tends to compile in Visual Studio 2022) -- Zircon source code has a Visual Studio 2022 solution file and last time I tried it, it compiled a month ago (I use Mingw in CodeBlocks to compile because I can statically link SDL2, eliminating need for a separate SDL2.dll).
> 
> Zircon: https://www.moddb.com/mods/zircon-engine/
> 
> https://www.moddb.com/mods/zircon-engine/downloads/zircon-beta-release-37-win64-linux-binaries-source is the latest.

I can't download Zircon from your first link because moddb says that there is no available mirror but I do can download the latest Zircon from your second link which not only downloads the .exe file that with it I can play Quake with realtime lighting, shadows, reflections, refractions and etc but it also downloads the source code of Zircon but it doesn't seem to contain any .sln file at all so I don't know how the source code of Zircon can be compiled with Visual Studio at all.

**Comment by Baker7** [comment]
> doesn't seem to contain any .sln file

Open the .vcxproj in Visual Studio 2022, that is the project file.

**Comment by FeatureRequestor** [comment]
> Thanks!
> 
> > doesn't seem to contain any .sln file
> 
> Open the .vcxproj in Visual Studio 2022, that is the project file.

I will try. Thanks.

**Comment by Baker7** [comment]
Unfortunately, I don't know much about Visual Studio 2022 -- I prefer an older version.  Visual Studio 2022 is a very nice IDE, but has too much stuff getting in my way I can't turn off.  I make sure it can build the engine once a month and otherwise use an older version.

**Comment by FeatureRequestor** [comment]
> Unfortunately, I don't know much about Visual Studio 2022 -- I prefer an older version. Visual Studio 2022 is a very nice IDE, but has too much stuff getting in my way I can't turn off. I make sure it can build the engine once a month and otherwise use an older version.

I agree. Microsoft Visual Studio is really complex IDE and it took me years to learn how to use it right.
