### ISSUE TITLE
TENEBRAE_GFX_DLIGHTS extension is not compatible with tenebrae

### ISSUE THREAD

**Issue by hemebond** [DarkPlacesEngine/darkplaces#131]
According to Spoike:

1. PFLAGS_FULLDYNAMIC should actually be EF_FULLDYNAMIC=16 instead.
2. IT SHOULD WORK WITH MAKESTATIC TOO

**Comment by Baker7** [comment]
Do you have a download link for Tenebrae that you are using?  EF_FULLDYNAMIC would conflict with EF_NODRAW (16),

Zircon supports extra stuff in static entities like .alpha and .effects like EF_NOSHADOW EF_ADDITIVE etc.  and DarkPlaces is more than welcome to use any of it, I could make ".pflags" part of the static entity extension. 

If you give me a link I'll look through it, I would expect DarkPlaces translates EF_FULLDYNAMIC to PFLAG_DYNAMIC but I haven't really dug into it because I don't have Tenebrae installed.

**Comment by hemebond** [comment]
> Do you have a download link for Tenebrae that you are using?

No, I'm not doing anything with Tenebrae. The only download link I could find was on https://quake.fandom.com/wiki/Tenebrae and it's an executable (self-extracting archive _I assume_).

> If you give me a link I'll look through it, I would expect DarkPlaces translates EF_FULLDYNAMIC to PFLAG_DYNAMIC but I haven't really dug into it because I don't have Tenebrae installed.

Unfortunately I don't have any more information. It was just mentioned in passing.

This is definitely a super-ultra-mega-low-priority given that no one uses Tenebrae anymore. If nothing else it might indicate the code around it can be deprecated.

**Comment by Baker7** [comment]
`	if (gamemode == GAME_TENEBRAE) {
		// tenebrae's EF_FULLDYNAMIC conflicts with Q2's EF_NODRAW_16
		if (effects & 16) {
			effects &= ~16;
			lightpflags |= PFLAGS_FULLDYNAMIC_128;
		}
`

Verified: DarkPlaces translates the 16 effects bit into PFLAGS_FULLDYNAMIC if game is .tenebrae.

/Static entities currently do not get effects in DarkPlaces, so static entities will not get an PFLAGS at all.

**Comment by hemebond** [comment]
I'm going to close this because I can't even find a version of Tenebrae I feel safe downloading and no one plays Tenebrae anyway. Perhaps the Tenebrae support can be removed entirely.
