### ISSUE TITLE
ent_create without arguments causes segfault

### ISSUE THREAD

**Issue by hemebond** [DarkPlacesEngine/DarkPlaces#199]
Loaded up e1m1 with sv_cheats enabled and typed `ent_create` command into the console without any arguments and it caused a segfault:

```
]ent_create

server EDICT 164:
origin         '575.968994 -112.632004 39.0764999'
classname      
Host_Error: SVVM_ExecuteProgram: 
SV_Shutdown
Client "player" dropped (Server shutting down)
CL_Disconnect
CSQC unloaded
Sending clc_disconnect
Disconnect: Host_Error: SVVM_ExecuteProgram: 
ERROR: can't deactivate vsync because No OpenGL context has been made current


    Engine Crash: Segmentation fault    
[0x560875fffc20]
DarkPlaces-Quake Linux v20140513-1571-g16ebb998~ Sep 18 2024 release GCC
```

The command should print help text when no arguments (or the wrong arguments) are provided.

**Comment by Baker7** [comment]
One of the shutdown changes implemented probably is causing this.

In Zircon, does not segfault on Windows.   Loaded Linux SDL version of Zircon via WSL and "ent_create" does not segfault either.

This probably also means the segfault can be caused by other methods that create a host error -- not just "ent_create_ failure.

Introduction
testing connected
testing entered the game
]ent_create

server EDICT 84:
origin         '544 1407.96997 50.0312996'
classname      
Host_Error: SVVM_ExecuteProgram: 
Client "testing" dropped (Server shutting down)
Disconnected

**Comment by hemebond** [comment]
This seems to have been resolved by 6cc81c6932cd76a2ab01956d39136c99a084a14f and the game no longer crashes when the command is used without arguments.

**Comment by Cloudwalk9** [comment]
Bigger issue might be the massive footgun failing to write boilerplate for each and every command for the no-args case presents. Separate bug though.

**Comment by Baker7** [comment]
Went to create an entity in CSQC ... then 2 things happened ...

1. I was expecting PRVM_EdictCreate or something ... couldn't find the command even with "find" (naming of ent_create is inconsistent with prvm_edictset and friends).

2. It isn't supported for client ... at all.  It is a server progs only command.

I guess I'll just throw some QuakeC in GameCommand to do that work for the moment but I was surprised I can't create or remove an entity in CSQC via the console.
