### ISSUE TITLE
Weapon modeling systems like v_*.md3 are originally *.iqm files, IQM compatibility problem

### ISSUE THREAD

**Issue by LegendaryGuard** [DarkPlacesEngine/darkplaces#39]
We found a model compatibility issue where stayed for years. 

The weird thing is that the modeler managed to rename the extension, *.iqm files to *.md3 ones in order to import and run successfully the models in the game.

We tried to change the code in QuakeC about definitions of weapon files like `g_electro.md3` to `g_electro.iqm`, `v_electro.md3` to `v_electro.iqm` ... Even changing ".iqm" string and removing line in [`qcsrc/common/weapons/all.qc`](https://gitlab.com/xonotic/xonotic-data.pk3dir/-/blob/master/qcsrc/common/weapons/all.qc#L424) But it didn't work...
<img src="https://user-images.githubusercontent.com/49716252/161638497-0f0f2299-c3e7-4cae-aba3-0f922e2ff4bc.jpg" alt="iqmnoncompatiblemd3" />

Logically, IQM should give support and shouldn't only work only using MD3 in this kind of cases.

Reference and more info: https://gitlab.com/xonotic/xonotic-data.pk3dir/-/issues/2629#note_686988936

We believe that a patch should solve this compatibility problem.

**Comment by Shpoike** [comment]
when extension changing is quite so common you can be sure that the engine doesn't really care if the last 3 letters of the filename matches some microsoft expectation for the file format inside.
The problem exists between Quake and Chair... err... in the QC, not the engine. If there's one hack making assumptions about the trailing part of filenames there's no doubt other instances of it elsewhere in the code, too. Hence why the modeler decided to just faff around with misleading people instead of using the typical filename postfix that you'd expect for that format.

**Comment by bones-was-here** [comment]
The .md3 extension isn't hard coded in DP, but is hard coded in multiple places in QC, so this issue needs to be filed at https://gitlab.com/xonotic/xonotic-data.pk3dir/-/issues
